clusterName: k8s
serverComponents:
  ubuntu:
    version: ubuntu-22.04
    username: hcloud-user
    architecture: x86
  kubernetes:
    version: 1.29.3-1.1
  docker:
    version: 5:24.0.6-1~ubuntu.$(lsb_release -rs)~$(lsb_release -cs)
  containerd:
    version: 1.6.24-1
    pausecontainer: registry.k8s.io/pause:3.2
ipRange: 10.0.0.0/16
ipRangeSubnet: 10.0.0.0/16
masterCount: 3
networkZone: eu-central
location: fsn1
datacenter: fsn1-dc14
masterServers:
  namepattern: master-%d
  placementgroupname: master-placement-group
  servertype: cx22
  labels:
    role: master
  waittimeinretry: 3s
  retrytimelimit: 20
  serversinitparams:
    targz: https://github.com/maksim-paskal/hcloud-k8s-ctl/archive/refs/heads/main.tar.gz
    folder: hcloud-k8s-ctl-main
masterLoadBalancer:
  loadbalancertype: lb11
  listenport: 6443
  destinationport: 6443
cliArgs:
  loglevel: DEBUG
  configpath: config.yaml
  saveconfigpath: ./e2e/configs/full.yaml
  action: save-full-config
  adhoccommand: ""
  adhoccopynewfile: false
  adhocmasters: false
  adhocworkers: true
  adhocuser: ""
  upgradecontrolplaneversion: ""
  createfirewallcontrolplane: false
  createfirewallworkers: false
deployments: {}
preStartScript: ""
postStartScript: ""
cluster-autoscaler:
  autoscalingGroups:
    - name: CPX11:FSN1:cpx11-fsn1
      minSize: 0
      maxSize: 20
    - name: CPX21:FSN1:cpx21-fsn1
      minSize: 0
      maxSize: 20
    - name: CX22:FSN1:cx22-fsn1
      minSize: 0
      maxSize: 20
    - name: CPX31:FSN1:cpx31-fsn1
      minSize: 0
      maxSize: 20
    - name: CX32:FSN1:cx32-fsn1
      minSize: 0
      maxSize: 20
    - name: CPX41:FSN1:cpx41-fsn1
      minSize: 0
      maxSize: 20
    - name: CX42:FSN1:cx42-fsn1
      minSize: 0
      maxSize: 20
    - name: CX52:FSN1:cx52-fsn1
      minSize: 0
      maxSize: 20
    - name: CPX51:FSN1:cpx51-fsn1
      minSize: 0
      maxSize: 20
    - name: CPX11:NBG1:cpx11-nbg1
      minSize: 0
      maxSize: 20
    - name: CPX21:NBG1:cpx21-nbg1
      minSize: 0
      maxSize: 20
    - name: CX22:NBG1:cx22-nbg1
      minSize: 0
      maxSize: 20
    - name: CPX31:NBG1:cpx31-nbg1
      minSize: 0
      maxSize: 20
    - name: CX32:NBG1:cx32-nbg1
      minSize: 0
      maxSize: 20
    - name: CPX41:NBG1:cpx41-nbg1
      minSize: 0
      maxSize: 20
    - name: CX42:NBG1:cx42-nbg1
      minSize: 0
      maxSize: 20
    - name: CX52:NBG1:cx52-nbg1
      minSize: 0
      maxSize: 20
    - name: CPX51:NBG1:cpx51-nbg1
      minSize: 0
      maxSize: 20
    - name: CPX11:HEL1:cpx11-hel1
      minSize: 0
      maxSize: 20
    - name: CPX21:HEL1:cpx21-hel1
      minSize: 0
      maxSize: 20
    - name: CX22:HEL1:cx22-hel1
      minSize: 0
      maxSize: 20
    - name: CPX31:HEL1:cpx31-hel1
      minSize: 0
      maxSize: 20
    - name: CX32:HEL1:cx32-hel1
      minSize: 0
      maxSize: 20
    - name: CPX41:HEL1:cpx41-hel1
      minSize: 0
      maxSize: 20
    - name: CX42:HEL1:cx42-hel1
      minSize: 0
      maxSize: 20
    - name: CX52:HEL1:cx52-hel1
      minSize: 0
      maxSize: 20
    - name: CPX51:HEL1:cpx51-hel1
      minSize: 0
      maxSize: 20
