clusterName: k8s
serverComponents:
  ubuntu:
    version: ubuntu-22.04
    username: hcloud-user
    architecture: x86
  kubernetes:
    version: 1.30.5-1.1
  docker:
    version: 5:27.3.1-1~ubuntu.$(lsb_release -rs)~$(lsb_release -cs)
  containerd:
    version: 1.7.22-1
    pausecontainer: registry.k8s.io/pause:3.2
ipRange: 10.0.0.0/16
ipRangeSubnet: 10.0.0.0/16
masterCount: 3
networkZone: eu-central
location: fsn1
datacenter: fsn1-dc14
masterServers:
  namepattern: master-%d
  placementgroupname: master-placement-group
  servertype: cx22
  labels:
    role: master
  waittimeinretry: 3s
  retrytimelimit: 20
  serversinitparams:
    targz: https://github.com/maksim-paskal/hcloud-k8s-ctl/archive/refs/heads/main.tar.gz
    folder: hcloud-k8s-ctl-main
masterLoadBalancer:
  loadbalancertype: lb11
  listenport: 6443
  destinationport: 6443
cliArgs:
  loglevel: DEBUG
  configpath: config.yaml
  saveconfigpath: ./e2e/configs/full.yaml
  action: save-full-config
  adhoccommand: ""
  adhoccopynewfile: false
  adhocmasters: false
  adhocworkers: true
  adhocuser: ""
  upgradecontrolplaneversion: ""
  createfirewallcontrolplane: false
  createfirewallworkers: false
deployments: {}
preStartScript: ""
postStartScript: ""
cluster-autoscaler:
  autoscalingGroups:
    - name: cpx11-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cpx11
      region: fsn1
    - name: cpx21-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cpx21
      region: fsn1
    - name: cx22-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cx22
      region: fsn1
    - name: cpx31-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cpx31
      region: fsn1
    - name: cx32-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cx32
      region: fsn1
    - name: cpx41-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cpx41
      region: fsn1
    - name: cx42-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cx42
      region: fsn1
    - name: cx52-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cx52
      region: fsn1
    - name: cpx51-fsn1
      minSize: 0
      maxSize: 20
      instanceType: cpx51
      region: fsn1
    - name: cpx11-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cpx11
      region: nbg1
    - name: cpx21-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cpx21
      region: nbg1
    - name: cx22-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cx22
      region: nbg1
    - name: cpx31-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cpx31
      region: nbg1
    - name: cx32-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cx32
      region: nbg1
    - name: cpx41-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cpx41
      region: nbg1
    - name: cx42-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cx42
      region: nbg1
    - name: cx52-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cx52
      region: nbg1
    - name: cpx51-nbg1
      minSize: 0
      maxSize: 20
      instanceType: cpx51
      region: nbg1
    - name: cpx11-hel1
      minSize: 0
      maxSize: 20
      instanceType: cpx11
      region: hel1
    - name: cpx21-hel1
      minSize: 0
      maxSize: 20
      instanceType: cpx21
      region: hel1
    - name: cx22-hel1
      minSize: 0
      maxSize: 20
      instanceType: cx22
      region: hel1
    - name: cpx31-hel1
      minSize: 0
      maxSize: 20
      instanceType: cpx31
      region: hel1
    - name: cx32-hel1
      minSize: 0
      maxSize: 20
      instanceType: cx32
      region: hel1
    - name: cpx41-hel1
      minSize: 0
      maxSize: 20
      instanceType: cpx41
      region: hel1
    - name: cx42-hel1
      minSize: 0
      maxSize: 20
      instanceType: cx42
      region: hel1
    - name: cx52-hel1
      minSize: 0
      maxSize: 20
      instanceType: cx52
      region: hel1
    - name: cpx51-hel1
      minSize: 0
      maxSize: 20
      instanceType: cpx51
      region: hel1
