# Kubernetes v1.28 in Europe
ipRange: "10.0.0.0/16"
masterCount: 3
serverComponents:
  kubernetes:
    version: 1.28.2
  docker:
    version: 5:24.0.6-1~ubuntu.20.04~focal
  containerd:
    version: 1.6.24-1
