# Kubernetes v1.28 in Europe (ARM64 architecture)
ipRange: "10.0.0.0/16"
masterCount: 3
serverComponents:
  ubuntu:
    architecture: arm
  kubernetes:
    version: 1.28.2
  docker:
    version: 5:24.0.6-1~ubuntu.20.04~focal
  containerd:
    version: 1.6.24-1
masterServers:
  servertype: cax11
cluster-autoscaler:
  autoscalingGroups:
  - name: CAX41:FSN1:cax-fsn1
    minSize: 1
    maxSize: 20