# Kubernetes v1.28 in US East
ipRange: "10.0.0.0/16"
masterCount: 3
networkZone: us-east
location: ash
datacenter: ash-dc1
masterServers:
  servertype: cpx21
serverComponents:
  kubernetes:
    version: 1.28.2
  docker:
    version: 5:24.0.6-1~ubuntu.20.04~focal
  containerd:
    version: 1.6.24-1
cluster-autoscaler:
  autoscalingGroups:
  - name: CPX51:ASH:cpx51-ash
    minSize: 1
    maxSize: 20