# Kubernetes v1.30 in Europe
ipRange: "10.0.0.0/16"
masterCount: 3
serverComponents:
  ubuntu:
    version: ubuntu-20.04
    architecture: x86
  kubernetes:
    version: 1.30.5-1.1
  docker:
    version: 5:27.3.1-1~ubuntu.$(lsb_release -rs)~$(lsb_release -cs)
  containerd:
    version: 1.7.22-1
