# Kubernetes v1.32 in Europe
ipRange: "10.0.0.0/16"
masterCount: 3
serverComponents:
  ubuntu:
    version: ubuntu-24.04
    architecture: x86
  kubernetes:
    version: 1.32.3-1.1
  docker:
    version: 5:28.1.0-1~ubuntu.$(lsb_release -rs)~$(lsb_release -cs)
  containerd:
    version: 1.7.27-1
masterServers:
  servertype: cpx21
