# Kubernetes v1.30 in Europe (ARM64 architecture)
ipRange: "10.0.0.0/16"
masterCount: 3
serverComponents:
  ubuntu:
    version: ubuntu-22.04
    architecture: arm
  kubernetes:
    version: 1.31.4-1.1
  docker:
    version: 5:27.4.1-1~ubuntu.$(lsb_release -rs)~$(lsb_release -cs)
  containerd:
    version: 1.7.24-1
masterServers:
  servertype: cax11
cluster-autoscaler:
  autoscalingGroups:
  - name: cax-fsn1
    minSize: 1
    maxSize: 20
    instanceType: cax41
    region: fsn1
