ipRange: "10.0.0.0/16"
masterCount: 3
serverComponents:
  ubuntu:
    version: ubuntu-24.04
# files for custom install
# masterServers:
#   serversinitparams:
#     targz: https://github.com/maksim-paskal/hcloud-k8s-ctl/archive/refs/heads/prepare-to-ubuntu-22.04.tar.gz
#     folder: hcloud-k8s-ctl-prepare-to-ubuntu-22.04