ipRange: "10.0.0.0/16"
masterCount: 3
# files for custom install
# masterServers:
#   serversinitparams:
#       targz: https://github.com/maksim-paskal/hcloud-k8s-ctl/archive/refs/heads/add-post-install.tar.gz
#       folder: hcloud-k8s-ctl-add-post-install