clusterName: k8s
kubeConfigPath: ~/.kube/hcloud
hetznerToken: some-token-string
ipRange: 10.0.0.0/16
sshPrivateKey: ~/.ssh/id_rsa
sshPublicKey: ~/.ssh/id_rsa.pub
masterCount: 3
networkZone: us-east
location: fsn1
datacenter: fsn1-dc14
masterServers:
  namepattern: master-%d
  servertype: cx21
  image: ubuntu-20.04
  labels:
    role: master
  waittimeinretry: 3s
  retrytimelimit: 20
  serversinitparams:
    targz: https://github.com/maksim-paskal/hcloud-k8s-ctl/archive/refs/heads/main.tar.gz
    folder: hcloud-k8s-ctl-main
masterLoadBalancer:
  loadbalancertype: lb11
  listenport: 6443
  destinationport: 6443
cliArgs:
  loglevel: INFO
  configpath: config.yaml
  action: list-configurations
deploymentsConfig:
  ccmconfig:
    env:
      - name: HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP
        value: "true"
      - name: HCLOUD_LOAD_BALANCERS_LOCATION
        value: "{{ lower .Values.location }}"
