clusterName: k8s
kubeConfigPath: /Users/mpascal/.kube/hcloud
hetznerToken:
    main: <secret>
    csi: ""
    ccm: ""
serverComponents:
    ubuntu:
        version: ubuntu-20.04
        username: hcloud-user
        architecture: x86
    kubernetes:
        version: 1.24.9
    docker:
        version: 5:20.10.17~3-0~ubuntu-focal
    containerd:
        version: 1.6.6-1
        pausecontainer: k8s.gcr.io/pause:3.2
ipRange: 10.0.0.0/16
ipRangeSubnet: 10.0.0.0/16
sshPrivateKey: /Users/mpascal/.ssh/id_rsa
sshPublicKey: /Users/mpascal/.ssh/id_rsa.pub
masterCount: 3
networkZone: eu-central
location: fsn1
datacenter: fsn1-dc14
masterServers:
    namepattern: master-%d
    placementgroupname: master-placement-group
    servertype: cx21
    labels:
        role: master
    waittimeinretry: 3s
    retrytimelimit: 20
    serversinitparams:
        targz: https://github.com/maksim-paskal/hcloud-k8s-ctl/archive/refs/heads/main.tar.gz
        folder: hcloud-k8s-ctl-main
masterLoadBalancer:
    loadbalancertype: lb11
    listenport: 6443
    destinationport: 6443
cliArgs:
    loglevel: DEBUG
    configpath: config.yaml
    saveconfigpath: ./examples/config-full.yaml
    action: save-full-config
    adhoccommand: ""
    adhoccopynewfile: false
    adhocmasters: false
    adhocworkers: true
    adhocuser: ""
    upgradecontrolplaneversion: ""
    createfirewallcontrolplane: false
    createfirewallworkers: false
deployments: {}
autoscaler:
    enabled: true
    image: docker.io/paskalmaksim/cluster-autoscaler-amd64:fc3aefc3d
    args:
        - --v=4
        - --cloud-provider=hetzner
        - --stderrthreshold=info
        - --expander=least-waste
        - --scale-down-enabled=true
        - --skip-nodes-with-local-storage=false
        - --skip-nodes-with-system-pods=false
        - --scale-down-utilization-threshold=0.8
    defaults:
        min: 0
        max: 20
    workers:
        - location: fsn1
          min: 0
          max: 0
          type:
            - cx21
            - cpx21
            - cx31
            - cpx31
            - cx41
            - cpx41
            - cx51
            - cpx51
        - location: nbg1
          min: 0
          max: 0
          type:
            - cx21
            - cpx21
            - cx31
            - cpx31
            - cx41
            - cpx41
            - cx51
            - cpx51
        - location: hel1
          min: 0
          max: 0
          type:
            - cx21
            - cpx21
            - cx31
            - cpx31
            - cx41
            - cpx41
            - cx51
            - cpx51
preStartScript: ""
postStartScript: ""
