apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-autoscaler
  labels:
    app: test-autoscaler
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test-autoscaler
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: test-autoscaler
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - test-autoscaler
            topologyKey: kubernetes.io/hostname
      containers:
      - name: test-autoscaler
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "7"
            memory: 15Gi
        command:
        - sleep
        - 1d