apiVersion: v2
name: hcloud-k8s-ctl
version: 0.0.2
dependencies:
- name: nfs-subdir-external-provisioner
  version: "4.0.16"
  repository: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"
  condition: deployments.nfs.nfs-subdir-external-provisioner.enabled
- name: kubelet-csr-approver
  version: "0.2.3"
  repository: https://postfinance.github.io/kubelet-csr-approver
- name: hcloud-csi
  version: "2.5.1"
  repository: https://charts.hetzner.cloud
- name: hcloud-cloud-controller-manager
  version: "v1.18.0"
  repository: https://charts.hetzner.cloud
- name: cluster-autoscaler
  version: "9.29.4"
  repository: https://kubernetes.github.io/autoscaler
- name: metrics-server
  version: "3.11.0"
  repository: https://kubernetes-sigs.github.io/metrics-server
- name: flannel
  version: "v0.22.3"
  repository: https://flannel-io.github.io/flannel