hetznerToken:
  main: some-token-string
  csi: null
  ccm: null
clusterName: k8s
location: nbg1
autoscaler:
  enabled: true
  args:
  - --v=4
  - --cloud-provider=hetzner
  - --stderrthreshold=info
  - --expander=least-waste
  - --scale-down-enabled=true
  - --skip-nodes-with-local-storage=false
  - --skip-nodes-with-system-pods=false
  - --scale-down-utilization-threshold=0.8
  defaults:
    min: 0
    max: 20
  workers:
  - location: ""
    min: 0
    max: 0
    type:
    - cx11  
    - cx21
    - cpx31
    - cpx41
    - cx51
    - cpx51
deployments:
  nfs:
    server:
      enabled: false
      clusterIP: 10.100.0.100
    nfs-subdir-external-provisioner:
      enabled: false
  registry:
    enabled: false
    replicas: 2
    secret: somesecret
    image: registry:2.8.1
    imagePullPolicy: IfNotPresent
    clusterIP: "10.100.0.11"
    env: {}
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
  ccmconfig:
    env:
    - name: HCLOUD_NETWORK
      value: "{{ .Values.clusterName }}"
    - name: HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP
      value: "true"
    - name: HCLOUD_LOAD_BALANCERS_LOCATION
      value: "{{ lower .Values.location }}"

nfs-subdir-external-provisioner:
  replicaCount: 2
  fullnameOverride: nfs-subdir-external-provisioner
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
  nfs:
    server: 10.100.0.100
    path: /
    mountOptions:
    - nconnect=8  # only supported on linux kernel version >= 5.3
    - nfsvers=4.1
  storageClass:
    name: nfs
    archiveOnDelete: false

kubelet-csr-approver:
  bypassDnsResolution: true