clusterName: k8s
location: nbg1
workersCount: 20
autoscaler:
  enabled: true
  args:
  - --v=4
  - --cloud-provider=hetzner
  - --stderrthreshold=info
  - --expander=least-waste
  - --scale-down-enabled=true
  - --skip-nodes-with-local-storage=false
  - --skip-nodes-with-system-pods=false
  - --scale-down-utilization-threshold=0.8
  workers:
  - datacenter: ""
    min: 0
    max: 20
    type:
    - cx11  
    - cx21
    - cpx31
    - cpx41
    - cx51
    - cpx51
deploymentsConfig:
  registry:
    enabled: false
    replicas: 2
    secret: somesecret
    image: registry:2.8.1
    imagePullPolicy: IfNotPresent
    clusterIP: "10.100.0.11"
    env: {}
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
  ccmconfig:
    env:
    - name: HCLOUD_NETWORK
      value: "{{ .Values.clusterName }}"
    - name: HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP
      value: "true"
    - name: HCLOUD_LOAD_BALANCERS_LOCATION
      value: "{{ lower .Values.location }}"
