# separates tokens need to minimize error rate limit
apiVersion: v1
kind: Secret
metadata:
  name: hcloud
type: Opaque
data:
  token: {{ .Values.hetznerToken | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-csi
type: Opaque
data:
  token: {{ .Values.hetznerToken | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-ccm
type: Opaque
data:
  token: {{ .Values.hetznerToken | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hcloud-ccm-env
data:
  HCLOUD_NETWORK: {{ .Values.clusterName | quote }}
  HCLOUD_LOAD_BALANCERS_LOCATION: {{ lower .Values.location | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-env
data:
  HCLOUD_IMAGE: {{ .Values.serverComponents.ubuntu.version | quote }}
  HCLOUD_SSH_KEY: {{ .Values.clusterName | quote }}
  HCLOUD_NETWORK: {{ .Values.clusterName | quote }}