on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Hetzner Cloud API token'
        required: true

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.22'
    - uses: actions/checkout@v2
    - run: ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
    - run: make e2e branch=$GITHUB_HEAD_REF
      env:
        HCLOUD_TOKEN: ${{ github.event.inputs.token }}