on:
  workflow_dispatch:
  pull_request:

jobs:
  e2e:
    name: e2e
    runs-on: self-hosted
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - uses: actions/checkout@v2
    - run: make e2e branch=$GITHUB_HEAD_REF