on:
  workflow_dispatch:
    inputs:
      hcloud_token:
        description: 'Hetzner Cloud API token'
        required: true
      e2e_file_name:
        description: 'Name of the e2e tests'
        required: false
        default: 'v1.30*'
      debug:
        type: choice
        description: 'Debug mode'
        required: false
        options: ['true', 'false']
        default: 'false'

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.23'
    - uses: actions/checkout@v2
    - run: ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
    - run: make e2e branch=${{ github.base_ref || github.ref_name }}
      env:
        HCLOUD_TOKEN: ${{ github.event.inputs.hcloud_token }}
        E2E_FILE_NAME: ${{ github.event.inputs.e2e_file_name }}
        DEBUG: ${{ github.event.inputs.debug }}